.TH SYNDIE "1" "October 2006" "syndie" "User Commands"
.SH NAME
syndie \- interact with the Syndie distributed forum
.SH SYNOPSIS
.B syndie
[\fI@script_path\fR] [\fIdata_path\fR]
.br
.SH DESCRIPTION
.PP
Launch the text-only scriptable Syndie interface.
.TP
\fBscript_path\fR
Run the given script
.TP
\fBdata_path\fR
Use the given directory as the root Syndie path for
loading the archive, database, etc.  If not specified,
Syndie uses ${HOME}/.syndie/ as the root path.
.SH AUTHOR
Written by jrandom
.SH "REPORTING BUGS"
Report bugs to <syndie-dev@i2p.net>.
.SH COPYRIGHT
Copyright is theft.  Syndie is in the public domain.
.br
.SH "SEE ALSO"
Syndie's documentation is primarily in HTML, located in the
Syndie installation directory or
.B http://syndie.i2p.net/
